Failed attempt at making the communication methods standalone functions.
The build fails because the asyn user structure is protected:

In file included from /home/beams/KPETERSN/epics/motor-devel/support/asyn-R4-42/include/asynStandardInterfaces.h:20,
                 from /home/beams/KPETERSN/epics/motor-devel/support/asyn-R4-42/include/asynPortDriver.h:11,
                 from ../SPiiPlusComm.cpp:6:
../SPiiPlusComm.cpp: In function ‘asynStatus writeReadInt(asynPortDriver*, std::stringstream&, int*)’:
../SPiiPlusComm.cpp:26:17: error: ‘asynUser* asynPortDriver::pasynUserSelf’ is protected within this context
  asynPrint(apd->pasynUserSelf, ASYN_TRACEIO_DRIVER, "%s:%s: output = %s\n", driverName, functionName, cmd.str().c_str());
                 ^~~~~~~~~~~~~
/home/beams/KPETERSN/epics/motor-devel/support/asyn-R4-42/include/asynDriver.h:285:32: note: in definition of macro ‘asynPrint’
    ((pasynTrace->getTraceMask((pasynUser))&(reason)) \
                                ^~~~~~~~~